version: '3.8'

services:
  deuda-crediticia-app:
    build: .
    container_name: deuda-crediticia-app
    ports:
      - "3001:3000"
  
  nginx:
    image: nginx:latest
    container_name: nginx-deuda-crediticia
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - deuda-crediticia-app
